# PR Factory V7 high-risk test change
risk:low:
  - changed-files:
      - any-glob-to-any-file:
          - "docs/**"
          - "**/*.md"
          - "public/**"

risk:high:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**"
          - "src/**"
          - "supabase/**"
          - "infra/**"
          - "scripts/**"
          - "docker/**"
          - "package.json"
          - "package-lock.json"
          - "vite.config.ts"
          - "tailwind.config.ts"
          - "tsconfig*.json"
          - "eslint.config.js"

area:frontend:
  - changed-files:
      - any-glob-to-any-file:
          - "src/**"

area:supabase:
  - changed-files:
      - any-glob-to-any-file:
          - "supabase/**"

area:github:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**"

area:infra:
  - changed-files:
      - any-glob-to-any-file:
          - "infra/**"

type:deps:
  - changed-files:
      - any-glob-to-any-file:
          - "package.json"
          - "package-lock.json"
